# @package _global_

dataset:
  view_sampler:
    min_distance_between_context_views: 5
    max_distance_between_context_views: 10
    min_distance_to_context_views: 1
    warm_up_steps: 0
    initial_min_distance_between_context_views: 5
    initial_max_distance_between_context_views: 10
    num_target_views: 1